import type { Member, Transaction, SavingsAccount, Loan, CashbookEntry } from "./types";

export const members: Member[] = [
  {
    id: "1",
    name: "Anathalie Mukamana",
    memberId: "MEM001",
    joinDate: "2023-01-15",
    savingsBalance: 5200,
    loanBalance: 15000,
    status: "Active",
    avatarId: "avatar1",
  },
  {
    id: "2",
    name: "Jean Bosco Nsengiyumva",
    memberId: "MEM002",
    joinDate: "2023-02-20",
    savingsBalance: 7800,
    loanBalance: 0,
    status: "Active",
    avatarId: "avatar2",
  },
  {
    id: "3",
    name: "Clementine Uwera",
    memberId: "MEM003",
    joinDate: "2023-03-10",
    savingsBalance: 2101,
    loanBalance: 5000,
    status: "Active",
    avatarId: "avatar3",
  },
  {
    id: "4",
    name: "Emmanuel Habimana",
    memberId: "MEM004",
    joinDate: "2023-04-05",
    savingsBalance: 10500,
    loanBalance: 25000,
    status: "Active",
    avatarId: "avatar4",
  },
  {
    id: "5",
    name: "Solange Irakoze",
    memberId: "MEM005",
    joinDate: "2023-05-25",
    savingsBalance: 320,
    loanBalance: 0,
    status: "Inactive",
    avatarId: "avatar5",
  },
];

export const transactions: Transaction[] = [
  {
    id: "txn1",
    member: { name: "Anathalie Mukamana", avatarId: "avatar1" },
    type: "Deposit",
    amount: 500,
    date: "2024-07-28",
    status: "Completed",
  },
  {
    id: "txn2",
    member: { name: "Clementine Uwera", avatarId: "avatar3" },
    type: "Loan Repayment",
    amount: 1200,
    date: "2024-07-27",
    status: "Completed",
  },
  {
    id: "txn3",
    member: { name: "Emmanuel Habimana", avatarId: "avatar4" },
    type: "Loan Disbursement",
    amount: 10000,
    date: "2024-07-26",
    status: "Completed",
  },
  {
    id: "txn4",
    member: { name: "Jean Bosco Nsengiyumva", avatarId: "avatar2" },
    type: "Deposit",
    amount: 1000,
    date: "2024-07-25",
    status: "Completed",
  },
  {
    id: "txn5",
    member: { name: "Anathalie Mukamana", avatarId: "avatar1" },
    type: "Withdrawal",
    amount: 200,
    date: "2024-07-24",
    status: "Completed",
  },
];

export const savingsAccounts: SavingsAccount[] = [
  {
    id: "sav1",
    memberId: "1",
    memberName: "Anathalie Mukamana",
    accountNumber: "SAV001",
    type: "Compulsory",
    balance: 5200,
    openDate: "2023-01-15",
  },
  {
    id: "sav2",
    memberId: "2",
    memberName: "Jean Bosco Nsengiyumva",
    accountNumber: "SAV002",
    type: "Voluntary",
    balance: 7800,
    openDate: "2023-02-20",
  },
  {
    id: "sav3",
    memberId: "3",
    memberName: "Clementine Uwera",
    accountNumber: "SAV003",
    type: "Compulsory",
    balance: 2101,
    openDate: "2023-03-10",
  },
];

export const loans: Loan[] = [
  {
    id: "loan1",
    memberId: "1",
    memberName: "Anathalie Mukamana",
    loanId: "LN001",
    principal: 20000,
    balance: 15000,
    interestRate: 10,
    issueDate: "2024-03-01",
    dueDate: "2024-08-01",
    status: "Active",
  },
  {
    id: "loan2",
    memberId: "3",
    memberName: "Clementine Uwera",
    loanId: "LN002",
    principal: 5000,
    balance: 5000,
    interestRate: 12,
    issueDate: "2024-06-15",
    dueDate: "2024-09-15",
    status: "Active",
  },
  {
    id: "loan3",
    memberId: "4",
    memberName: "Emmanuel Habimana",
    loanId: "LN003",
    principal: 30000,
    balance: 25000,
    interestRate: 8,
    issueDate: "2024-01-20",
    dueDate: "2024-07-20",
    status: "Overdue",
  },
  {
    id: "loan4",
    memberId: "5",
    memberName: "Solange Irakoze",
    loanId: "LN004",
    principal: 10000,
    balance: 0,
    interestRate: 10,
    issueDate: "2023-09-01",
    dueDate: "2024-03-01",
    status: "Paid",
  },
];

export const income: CashbookEntry[] = [
    { id: 'inc1', date: '2024-07-01', description: 'Loan Interest - Anathalie Mukamana', category: 'Loan Interest', amount: 150 },
    { id: 'inc2', date: '2024-07-05', description: 'Late Payment Fees', category: 'Fees', amount: 50 },
    { id: 'inc3', date: '2024-07-10', description: 'Group Contribution', category: 'Contributions', amount: 1000 },
];

export const expenses: CashbookEntry[] = [
    { id: 'exp1', date: '2024-07-02', description: 'Office Stationery', category: 'Office Supplies', amount: 76 },
    { id: 'exp2', date: '2024-07-15', description: 'Bank Charges', category: 'Bank Fees', amount: 25 },
    { id: 'exp3', date: '2024-07-20', description: 'Software Subscription', category: 'IT', amount: 100 },
];

export const chartData = [
  { month: "Jan", savings: 4000, loans: 2400 },
  { month: "Feb", savings: 3000, loans: 1398 },
  { month: "Mar", savings: 2000, loans: 9800 },
  { month: "Apr", savings: 2780, loans: 3908 },
  { month: "May", savings: 1890, loans: 4800 },
  { month: "Jun", savings: 2390, loans: 3800 },
  { month: "Jul", savings: 3490, loans: 4300 },
];
